- name: Set up multiple authorized keys
  authorized_key:
    user: a
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/some-user.pub

#- name: Ensure kernel is at the latest version 
#  yum: name=kernel state=latest

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes
- name: Install OpenJDK Java
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   openjdk-8-jdk
  become: yes
- name: Install Netcat
  apt: name=nmap-ncat state=latest
  become: yes
